#!/bin/sh

DIR=`dirname $0`
if [ $DIR = . ]; then
    DIR=$PWD
else
    cd $DIR
fi

BUILD_DIR=$DIR/build
BUILD_LIB_DIR=$BUILD_DIR/usr/lib/i386-linux-gnu

rm -rf $BUILD_DIR
mkdir -p $BUILD_LIB_DIR

make clean all
cp rtwrapper.so $BUILD_LIB_DIR
cp -r debian $BUILD_DIR/DEBIAN
dpkg-deb -b build rtwrapper.deb
